menu:
  home: /
  posts: /archives/
  slides: /slides/
  resume: /resume/
  about: /about/

social:
  github: https://github.com/AlanSyue
  linkedin: https://www.linkedin.com/in/alan-syue-284a83134/
  twitter: https://twitter.com/alansyue
  email: mailto:me@alansyue.cc

footer:
  copyright: "Alan Syue"
  since: 2021
